package main

import (
	"fmt"
	"os"
	"path/filepath"

	"docit/internal/config"
	"docit/internal/generator"
	"docit/internal/parser"
)

func main() {
	cfgPath := "docit.yaml"

	if len(os.Args) > 1 {
		if os.Args[1] == "-h" || os.Args[1] == "--help" {
			printHelp()
			return
		}
		if os.Args[1] == "init" {
			initProject()
			return
		}
		cfgPath = os.Args[1]
	}

	cfg, err := config.Load(cfgPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}

	files, err := cfg.GetMarkdownFiles()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading markdown files: %v\n", err)
		os.Exit(1)
	}

	if len(files) == 0 {
		fmt.Println("No markdown files found in", cfg.SourceDir)
		os.Exit(1)
	}

	fmt.Printf("Found %d markdown files\n", len(files))

	var docs []*parser.Document
	for _, file := range files {
		fmt.Printf("Parsing: %s\n", file)
		doc, err := parser.Parse(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", file, err)
			continue
		}
		docs = append(docs, doc)
	}

	fmt.Printf("Generating %d HTML files...\n", len(docs))
	gen := generator.New(cfg, docs)
	if err := gen.Generate(); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Done! Output in %s\n", cfg.OutputDir)
}

func printHelp() {
	fmt.Println("Docit - Static Documentation Generator")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  docit              Run with default config (docit.yaml)")
	fmt.Println("  docit <config>     Run with custom config file")
	fmt.Println("  docit init         Initialize a new project")
}

func initProject() {
	dirs := []string{"docs"}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error creating directory %s: %v\n", dir, err)
			os.Exit(1)
		}
	}

	readmeContent := `---
title: Welcome
description: Welcome to Docit documentation
---

# Welcome to Docit

This is a static documentation site generated by **Docit**.

## Features

- Markdown support
- Clean, minimal design
- No JavaScript required
- Responsive layout

## Getting Started

1. Add your markdown files to the docs folder
2. Edit docit.yaml to configure your site
3. Run docit to generate the static site

## Code Example

    func main() {
        fmt.Println("Hello, Docit!")
    }

Enjoy your documentation!
`

	indexPath := filepath.Join("docs", "index.md")
	if err := os.WriteFile(indexPath, []byte(readmeContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating index.md: %v\n", err)
		os.Exit(1)
	}

	configContent := `title: "Docit Docs"
description: "Documentation for Docit"
sourceDir: "docs"
outputDir: "dist"
theme:
  primaryColor: "#3b82f6"
nav:
  - text: "Home"
    link: "index.html"
  - text: "GitHub"
    link: "https://github.com"
sidebar:
  - title: "Getting Started"
    items:
      - "index.md"
`

	if err := os.WriteFile("docit.yaml", []byte(configContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating docit.yaml: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Project initialized!")
	fmt.Println("  - docs/index.md")
	fmt.Println("  - docit.yaml")
	fmt.Println("")
	fmt.Println("Run 'docit' to build your site")
}